# fly.toml app configuration file generated for alpha-ai-systems on 2025-11-25T17:51:17Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'alpha-ai-systems'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 4
  memory_mb = 2048
